spring:
  application:
    name: oracle store
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:ORCLCDB
    username: store
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariPoolBooks
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:
    clean-history-on-start: true
    name: oracle_test.log
